@BaseUrl = http://localhost:8000

### Setup - Create first superadmin (only works once)
POST {{BaseUrl}}/setup
Content-Type: application/json

{
    "first_name": "Mapa",
    "last_name": "Digital",
    "email": "admin@admin.com",
    "password": "admin123"
}
