name: Deploy to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy-to-ec2:
    name: Deploy to EC2
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Criar arquivo .env de Produção
        run: |
          echo "PYTHONPATH=src" > .env
          echo "TEST_VARIABLE=something" >> .env
          echo "JWT_ALGORITHM=HS256" >> .env
          echo "JWT_EXPIRATION_MINUTES=30" >> .env
          
          echo "BASE_URL=http://3.128.24.232:8000" >> .env
          
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env
          
          echo "DATABASE_URL=postgresql+asyncpg://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@db:5432/${{ secrets.POSTGRES_DB }}" >> .env
          
          echo "JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}" >> .env
          echo "PASSWORD_PEPPER=${{ secrets.PASSWORD_PEPPER }}" >> .env

      - name: Subir containers de produção
        run: |
          docker compose -f docker-compose-prod.yml down
          docker compose -f docker-compose-prod.yml up -d --build
