name: Deploy to EC2

on:
  push:
    branches: [ "main", "mm/upload-to-s3" ]

jobs:
  deploy-to-ec2:
    name: Deploy to EC2
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Criar arquivo .env de Produção
        run: |
          echo "JWT_ALGORITHM=HS256" > .env
          echo "JWT_EXPIRATION_MINUTES=30" >> .env

          echo "BASE_URL=${{ secrets.BASE_URL }}" >> .env
          
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env
          
          echo "DATABASE_URL=postgresql+asyncpg://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@db:5432/${{ secrets.POSTGRES_DB }}" >> .env
          
          echo "JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}" >> .env
          echo "PASSWORD_PEPPER=${{ secrets.PASSWORD_PEPPER }}" >> .env

          echo "STORAGE_BACKEND=s3" >> .env
          echo "AWS_S3_BUCKET=${{ secrets.AWS_S3_BUCKET_NAME }}" >> .env
          echo "AWS_S3_REGION=${{ secrets.AWS_DEFAULT_REGION }}" >> .env
          echo "AWS_ACCESS_KEY_ID=${{ secrets.BACKEND_AWS_ACCESS_KEY_ID }}" >> .env
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.BACKEND_AWS_SECRET_ACCESS_KEY }}" >> .env

      - name: Subir containers de produção
        run: |
          docker compose -f docker-compose-prod.yml down
          docker compose -f docker-compose-prod.yml up -d --build
